### ISSUE TITLE
Error on deploy (deploy:assets:precompile) - LoadError: libffi.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by maurosbu** [sass/sassc-rails#110]
I folks, I replaced sass-rails with sassc-rails and when I try to deploy my app (through capistrano) I get the following error:

	Tasks: TOP => deploy:assets:precompile
	(See full trace by running task with --trace)
	The deploy has failed with an error: Exception while executing as XYZ: rake exit status: 1
	rake stdout: rake aborted!
	LoadError: libffi.so.5: cannot open shared object file: No such file or directory - /var/www/runaway/shared/bundle/ruby/2.5.0/gems/ffi-1.9.25/lib/ffi_c.so
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/ffi-1.9.25/lib/ffi.rb:6:in `require'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/ffi-1.9.25/lib/ffi.rb:6:in `rescue in <top (required)>'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/ffi-1.9.25/lib/ffi.rb:3:in `<top (required)>'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-2.0.0/lib/sassc/native.rb:3:in `require'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-2.0.0/lib/sassc/native.rb:3:in `<top (required)>'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-2.0.0/lib/sassc.rb:7:in `require_relative'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-2.0.0/lib/sassc.rb:7:in `<top (required)>'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-rails-2.0.0/lib/sassc/rails.rb:5:in `require'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-rails-2.0.0/lib/sassc/rails.rb:5:in `<top (required)>'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-rails-2.0.0/lib/sassc-rails.rb:3:in `require_relative'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-rails-2.0.0/lib/sassc-rails.rb:3:in `<top (required)>'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `require'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler.rb:114:in `require'
	/var/www/runaway/releases/20181031125031/config/application.rb:21:in `<top (required)>'
	/var/www/runaway/releases/20181031125031/Rakefile:4:in `require'
	/var/www/runaway/releases/20181031125031/Rakefile:4:in `<top (required)>'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
	/usr/local/rvm/gems/ruby-2.5.3/bin/bundle:23:in `load'
	/usr/local/rvm/gems/ruby-2.5.3/bin/bundle:23:in `<main>'
	/usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
	/usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'

	Caused by:
	LoadError: cannot load such file -- 2.5/ffi_c
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/ffi-1.9.25/lib/ffi.rb:4:in `require'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/ffi-1.9.25/lib/ffi.rb:4:in `<top (required)>'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-2.0.0/lib/sassc/native.rb:3:in `require'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-2.0.0/lib/sassc/native.rb:3:in `<top (required)>'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-2.0.0/lib/sassc.rb:7:in `require_relative'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-2.0.0/lib/sassc.rb:7:in `<top (required)>'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-rails-2.0.0/lib/sassc/rails.rb:5:in `require'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-rails-2.0.0/lib/sassc/rails.rb:5:in `<top (required)>'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-rails-2.0.0/lib/sassc-rails.rb:3:in `require_relative'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/sassc-rails-2.0.0/lib/sassc-rails.rb:3:in `<top (required)>'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `require'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler.rb:114:in `require'
	/var/www/runaway/releases/20181031125031/config/application.rb:21:in `<top (required)>'
	/var/www/runaway/releases/20181031125031/Rakefile:4:in `require'
	/var/www/runaway/releases/20181031125031/Rakefile:4:in `<top (required)>'
	/var/www/runaway/shared/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	/usr/local/rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
	/usr/local/rvm/gems/ruby-2.5.3/bin/bundle:23:in `load'
	/usr/local/rvm/gems/ruby-2.5.3/bin/bundle:23:in `<main>'
	/usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
	/usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
	(See full trace by running task with --trace)
	rake stderr: Nothing written

Many thanks in advance for your help.

Mauro

**Comment by maurosbu** [comment]
Hi folks, 
this is a problem related to [ffi](https://rubygems.org/gems/ffi) gem, I have the same issue also with another gem depending on it.

In CentOS 7 there is a libffi.so.6 but not a libffi.so.5

**Comment by maurosbu** [comment]
Had to remove and reinstall the gem.
