### ISSUE TITLE
cannot load such file -- sprockets/cache/memory_store (LoadError)

### ISSUE THREAD

**Issue by mobilizer4you** [sass/sassc-rails#142]
**build issues**
/root/.rbenv/versions/2.6.3/bin/ruby: warning: shebang line ending with \r may cause problems
Traceback (most recent call last):
bin/rails: Bootsnap::LoadPathCache::FallbackScan
        92: from bin/rails:4:in `<main>'
        91: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
        90: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
        89: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
        88: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        87: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        86: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        85: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        84: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        83: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
        82: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
        81: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
        80: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        79: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        78: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        77: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `perform'
        76: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `tap'
        75: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:141:in `block in perform'
        74: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
        73: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
        72: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
        71: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        70: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        69: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        68: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        67: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        66: from /mnt/f/MDA/core/core/config/application.rb:7:in `<main>'
        65: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
        64: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
        63: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
        62: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
        61: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
        60: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
        59: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        58: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        57: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        56: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        55: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        54: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sass-rails-5.1.0/lib/sass-rails.rb:1:in `<main>'
        53: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
        52: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
        51: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
        50: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        49: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        48: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        47: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        46: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        45: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sass-rails-5.1.0/lib/sass/rails.rb:11:in `<main>'
        44: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
        43: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
        42: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
        41: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        40: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        39: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        38: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        37: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        36: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sass-rails-5.1.0/lib/sass/rails/railtie.rb:3:in `<main>'
        35: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
        34: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
        33: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
        32: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        31: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        30: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        29: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        28: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        27: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:6:in `<main>'
        26: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
        25: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
        24: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
        23: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        22: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        21: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        20: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        19: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        18: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets.rb:4:in `<main>'
        17: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
        16: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
        15: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
        14: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        13: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        12: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        11: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        10: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
         9: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/environment.rb:2:in `<main>'
         8: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
         7: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
         6: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
         5: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
         4: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:41:in `rescue in require'
         3: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
         2: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
         1: from /root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/root/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- sprockets/cache/memory_store (LoadError)

**Gemfile**
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
gem 'with_advisory_lock'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 4.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.7'

# HAML for beauty
gem 'haml'
gem "haml-rails", "~> 2.0"

# User Identity and Authentication
gem 'devise'
gem 'omniauth'

# Security and Obfuscation
gem 'hashid-rails'
gem 'audited'

# Background Tasks
gem 'sucker_punch'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# include ap in production to avoid errors
gem "awesome_print", require:"ap"

# JWT support
gem 'jwt'

# Grape for the API
gem 'grape'
gem 'grape-entity'
gem 'grape-middleware-logger'
gem 'grape-swagger'
gem 'grape-swagger-entity'
gem 'grape-swagger-representable'
gem 'grape-swagger-ui'
gem 'grape_logging'

# Server Health
gem 'sys-filesystem'
gem 'sys-proctable'
gem 'sys-cpu'

# Montioring and Alerting
gem 'rollbar'
gem 'airbrake'

# Twilio
gem 'twilio-ruby', '~> 5.31.5'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'bullet'
  gem 'factory_bot_rails'
  gem 'license_finder'
  gem 'rack-cors'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
#  gem 'better_errors'
  gem "binding_of_caller"
  gem 'pry', '~> 0.12.2'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'database_cleaner'
  gem 'simplecov', '~> 0.17.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'rack-cors'

**Comment by mobilizer4you** [comment]
rake aborted!
LoadError: cannot load such file -- sprockets/cache/memory_store
/mnt/f/MDA/core/core/config/application.rb:7:in `<top (required)>'
/mnt/f/MDA/core/core/rakefile:4:in `require_relative'
/mnt/f/MDA/core/core/rakefile:4:in `<top (required)>'

Caused by:
Bootsnap::LoadPathCache::FallbackScan:

**Comment by mobilizer4you** [comment]
Has someone solved these issues before?

**Comment by darryn02** [comment]
I had this issue and fixed it by reinstalling all my gems (`bundle install --force`). Strangely, while that got me going again in development, I still seem to get the same error running `rspec`...

**Comment by RobertGauld** [comment]
Did you manage to fix your rspec problem @darryn02, I'm now at right where you were.

**Comment by RobertGauld** [comment]
For the benefit of anyone who ends up here (like me) by searching for the message appearing in the title I found that clearing out the tmp/cache folder in my rails app fixed it.

**Comment by luigi7up** [comment]
I'm working with an app based on Rails 5.0.x and when I run `overmind start -f Procfile.dev`I am getting the `LoadError: cannot load such file -- sprockets/cache/memory_store` error:

```
[93184] ! Unable to load application: LoadError: cannot load such file -- sprockets/cache/memory_store
web    | Traceback (most recent call last):
web    | 	38: from /Users/amigost/.rvm/gems/ruby-2.7.3/bin/ruby_executable_hooks:22:in `<main>'
web    | 	37: from /Users/amigost/.rvm/gems/ruby-2.7.3/bin/ruby_executable_hooks:22:in `eval'
web    | 	36: from /Users/amigost/.rvm/gems/ruby-2.7.3/bin/puma:23:in `<main>'
web    | 	35: from /Users/amigost/.rvm/gems/ruby-2.7.3/bin/puma:23:in `load'
web    | 	34: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/puma-3.12.6/bin/puma:10:in `<top (required)>'
web    | 	33: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/puma-3.12.6/lib/puma/cli.rb:80:in `run'
web    | 	32: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/puma-3.12.6/lib/puma/launcher.rb:186:in `run'
web    | 	31: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/puma-3.12.6/lib/puma/cluster.rb:412:in `run'
web    | 	30: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/puma-3.12.6/lib/puma/runner.rb:147:in `load_and_bind'
web    | 	29: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/puma-3.12.6/lib/puma/configuration.rb:245:in `app'
web    | 	28: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/puma-3.12.6/lib/puma/configuration.rb:320:in `load_rackup'
web    | 	27: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/rack-2.2.6.4/lib/rack/builder.rb:66:in `parse_file'
web    | 	26: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/rack-2.2.6.4/lib/rack/builder.rb:105:in `load_file'
web    | 	25: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/rack-2.2.6.4/lib/rack/builder.rb:116:in `new_from_string'
web    | 	24: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/rack-2.2.6.4/lib/rack/builder.rb:116:in `eval'
web    | 	23: from config.ru:3:in `block in <main>'
web    | 	22: from config.ru:3:in `require_relative'
web    | 	21: from /Users/amigost/Projects/subastas/config/environment.rb:2:in `<top (required)>'
web    | 	20: from /Users/amigost/Projects/subastas/config/environment.rb:2:in `require_relative'
web    | 	19: from /Users/amigost/Projects/subastas/config/application.rb:6:in `<top (required)>'
web    | 	18: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/bundler-2.3.7/lib/bundler.rb:176:in `require'
web    | 	17: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/bundler-2.3.7/lib/bundler/runtime.rb:44:in `require'
web    | 	16: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/bundler-2.3.7/lib/bundler/runtime.rb:44:in `each'
web    | 	15: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/bundler-2.3.7/lib/bundler/runtime.rb:55:in `block in require'
web    | 	14: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/bundler-2.3.7/lib/bundler/runtime.rb:55:in `each'
web    | 	13: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/bundler-2.3.7/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
web    | 	12: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/bundler-2.3.7/lib/bundler/runtime.rb:60:in `require'
web    | 	11: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/sass-rails-5.0.7/lib/sass-rails.rb:1:in `<top (required)>'
web    | 	10: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/sass-rails-5.0.7/lib/sass-rails.rb:1:in `require'
web    | 	 9: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/sass-rails-5.0.7/lib/sass/rails.rb:11:in `<top (required)>'
web    | 	 8: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/sass-rails-5.0.7/lib/sass/rails.rb:11:in `require'
web    | 	 7: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/sass-rails-5.0.7/lib/sass/rails/railtie.rb:3:in `<top (required)>'
web    | 	 6: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/sass-rails-5.0.7/lib/sass/rails/railtie.rb:3:in `require'
web    | 	 5: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/sprockets-rails-3.2.2/lib/sprockets/railtie.rb:6:in `<top (required)>'
web    | 	 4: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/sprockets-rails-3.2.2/lib/sprockets/railtie.rb:6:in `require'
web    | 	 3: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/sprockets-3.7.2/lib/sprockets.rb:4:in `<top (required)>'
web    | 	 2: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/sprockets-3.7.2/lib/sprockets.rb:4:in `require'
web    | 	 1: from /Users/amigost/.rvm/gems/ruby-2.7.3/gems/sprockets-3.7.2/lib/sprockets/environment.rb:2:in `<top (required)>'
```

I am really not sure what this error means and i have tried:
- deleting the `tmp/cache` folder
- `bundle install --force`

to no avail...

I hope someone could help out with this one... It's an older project that I have and that I want to get up and running, but with this weird exception I can't start the server :/

**Comment by luigi7up** [comment]
Working on another project I solved a similar issue by running commenting out my whole Gemfile and then running 
`bundle clean --force`

I tried it on the problem I wrote about above and it worked

**Comment by luigi7up** [comment]
Hahahaahaha having the same problem 8 months later and the search for a solution gets me to the same thread where I answer my own question 🤦 
Confirming the steps:
1. Comment out the Gemfile
2. Run the `bundle clean --force`
3. Uncomment the Gemfile 
4. run `bundle install`
