### ISSUE TITLE
error reading values after Opacity

### ISSUE THREAD

**Issue by melnikaite** [sass/sassc-rails#16]
```
$ rails c staging
Loading staging environment (Rails 4.2.1)
2.2.1 :001 > Benchmark.bm { |bm| bm.report { Rails.application.assets["application.css"] } }
       user     system      total        real
 SassC::SyntaxError: Error: error reading values after Opacity
        on line 37 of ../../.rvm/gems/ruby-2.2.1@ws4be/gems/rails-assets-jgrowl-1.4.3/app/assets/stylesheets/jgrowl/jquery.jgrowl.scss
>> : progid:DXImageTransform.Microsoft.Alpha(Opacity=(0.9*100));
   ------------------------------------------^

	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sassc-1.1.2/lib/sassc/engine.rb:34:in `render'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sassc-rails-0.0.9/lib/sassc/rails/template.rb:54:in `evaluate'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sprockets-2.12.3/lib/sprockets/context.rb:197:in `block in evaluate'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `each'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `evaluate'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:12:in `initialize'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `new'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `block in build_asset'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sprockets-2.12.3/lib/sprockets/base.rb:395:in `circular_call_protection'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sprockets-2.12.3/lib/sprockets/base.rb:373:in `build_asset'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
... 17 levels...
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/melnikaite/projects/ws4be/bin/rails:8:in `<top (required)>'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/melnikaite/.rvm/gems/ruby-2.2.1@ws4be/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/melnikaite/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/melnikaite/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.2.1 :002 >
```

**Comment by bolandrm** [comment]
My inclination is that this bug report belongs in https://github.com/sass/libsass, but could you please post more of the stylesheet that's causing this?

**Comment by melnikaite** [comment]
It comes from here https://github.com/stanlemon/jGrowl/blob/1.4.3/jquery.jgrowl.css#L37-L38
jquery.jgrowl.scss is identical to jquery.jgrowl.css

**Comment by bolandrm** [comment]
This is now resolved (try the latest version of sassc-ruby).
