### ISSUE TITLE
Error during integration testing: ActionView::Template::Error: Error: Data context created with empty source string

### ISSUE THREAD

**Issue by fusion2004** [sass/sassc-rails#49]
My project is using ember-cli-rails to integrate the ember-cli assets into the asset pipeline, and I get this trace:

```
ActionView::Template::Error: Error: Data context created with empty source string

gems/sassc-1.8.1/lib/sassc/engine.rb:41:in `render'
gems/sassc-rails-1.1.0/lib/sassc/rails/compressor.rb:16:in `call'
gems/sprockets-3.5.2/lib/sprockets/sass_compressor.rb:28:in `call'
gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
gems/sprockets-3.5.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
gems/sprockets-3.5.2/lib/sprockets/loader.rb:60:in `block in load'
gems/sprockets-3.5.2/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
gems/sprockets-3.5.2/lib/sprockets/loader.rb:44:in `load'
gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `yield'
gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `load'
gems/sprockets-3.5.2/lib/sprockets/base.rb:66:in `find_asset'
gems/sprockets-3.5.2/lib/sprockets/base.rb:92:in `[]'
gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:123:in `asset_digest_path'
gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:76:in `compute_asset_path'
gems/actionview-4.2.4/lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:91:in `asset_path'
gems/actionview-4.2.4/lib/action_view/helpers/asset_url_helper.rb:267:in `stylesheet_path'
gems/actionview-4.2.4/lib/action_view/helpers/asset_tag_helper.rb:100:in `block in stylesheet_link_tag'
gems/actionview-4.2.4/lib/action_view/helpers/asset_tag_helper.rb:96:in `map'
gems/actionview-4.2.4/lib/action_view/helpers/asset_tag_helper.rb:96:in `stylesheet_link_tag'
gems/sprockets-rails-2.3.3/lib/sprockets/rails/helper.rb:170:in `stylesheet_link_tag'
gems/ember-cli-rails-0.5.8/app/helpers/ember_rails_helper.rb:27:in `include_ember_stylesheet_tags'
```

Any hints as to how I can hopefully resolve this?

**Comment by bolandrm** [comment]
It seems like maybe the filename/source is blank.

can you try this?
```
rails c
...
puts EmberCli::Assets.new(EmberCli["ember-app-name"]).stylesheet_assets
```

reference:
https://github.com/thoughtbot/ember-cli-rails/blob/2b26309c075e90c6e567df85bdde8d10f135dfd9/app/helpers/ember_rails_helper.rb#L25-L33

**Comment by fschwahn** [comment]
I just tried to deploy to Heroku and got the same error. I'm not using ember or ember-cli-rails in this project, so maybe it's not related to that. 

What's maybe helpful for resolving this: This only happens when the rails env is `production`, not in `development`.

My stacktrace:
```
SassC::SyntaxError: Error: Data context created with empty source string
gems/sassc-1.8.2/lib/sassc/engine.rb:41:in `render'
gems/sassc-rails-1.1.0/lib/sassc/rails/compressor.rb:16:in `call'
gems/sprockets-3.5.2/lib/sprockets/sass_compressor.rb:28:in `call'
gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
gems/sprockets-3.5.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
gems/sprockets-3.5.2/lib/sprockets/loader.rb:60:in `block in load'
gems/sprockets-3.5.2/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
gems/sprockets-3.5.2/lib/sprockets/loader.rb:44:in `load'
gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `yield'
gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `load'
gems/sprockets-3.5.2/lib/sprockets/base.rb:66:in `find_asset'
gems/sprockets-3.5.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
gems/sprockets-3.5.2/lib/sprockets/manifest.rb:134:in `block in find'
gems/sprockets-3.5.2/lib/sprockets/manifest.rb:133:in `each'
gems/sprockets-3.5.2/lib/sprockets/manifest.rb:133:in `find'
gems/sprockets-3.5.2/lib/sprockets/manifest.rb:168:in `compile'
gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
gems/sprockets-3.5.2/lib/rake/sprocketstask.rb:147:in `with_logger'
gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
```

**Comment by bolandrm** [comment]
Thanks for the stack trace, but I need some additional information to debug this...

Is it possible for you to set your local ENV to production and run `rake assets:precompile` and try to narrow down which CSS file is causing the problem?

**Comment by fschwahn** [comment]
Ok, I investigated a little more and I found the problem. Now I see you already hinted at it above: One of the CSS-files had no content. Ruby-Sass just swallows it and returns an empty string, but SassC throws an error:

```ruby
>> Sass::Engine.new('', style: :compressed).render # => ""
>> SassC::Engine.new('', style: :compressed).render # raises SassC::SyntaxError
```

So I think sassc-rails should guard against this behavior by checking for `input.empty?` in  `Sprockets::SassCompressor`. I can put together a pull request if you like.

**Comment by bolandrm** [comment]
Interesting.  I would like to try to solve this in https://github.com/sass/sassc-ruby.  If you'd like to open a pull request there, that would be great!

**Comment by fschwahn** [comment]
Sure, I'll have a look after the holidays.

**Comment by rubenswieringa** [comment]
Is this not just a matter of an early return in `Engine.render` or am I overlooking something? (and of course a test or two)

```diff
def render
+  return "" if @template.empty?
   data_context = Native.make_data_context(@template)
```

If you don't mind @fschwahn I can cook up a quick PR

**Comment by bolandrm** [comment]
There's a PR here https://github.com/sass/sassc-ruby/pull/31  which I just need to review and merge.

**Comment by rubenswieringa** [comment]
Cool!

**Comment by bolandrm** [comment]
If you're experiencing this issue, please try SassC-Ruby 1.8.3 (released last night).
