### ISSUE TITLE
cannot load such file -- sprockets/sass_template

### ISSUE THREAD

**Issue by schneems** [sass/sassc-rails#64]
Do you know where `require "sprockets/sass_template"` is supposed to be coming from?

```
LoadError: cannot load such file -- sprockets/sass_template
/Users/richardschneeman/.gem/ruby/2.4.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
/Users/richardschneeman/.gem/ruby/2.4.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
/Users/richardschneeman/.gem/ruby/2.4.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/richardschneeman/.gem/ruby/2.4.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
/Users/richardschneeman/.gem/ruby/2.4.0/gems/sassc-rails-1.2.1/lib/sassc/rails/template.rb:2:in `<top (required)>
```

Btw I maintain sprockets, sprockets-rails, and sass-rails now. Happy to work together to make the sassc-rails experience better in the future. For now i'm trying to get it to work with https://github.com/codetriage/codetriage and running into this error. 

Here's my bundle list https://gist.github.com/schneems/fdee966b8caf7556a79e4fcb23d7b41c

**Comment by schneems** [comment]
Ahh, it looks like those things got taken out in sprockets 4.x here's the 3.x branch https://github.com/rails/sprockets/blob/3.x/lib/sprockets/sass_template.rb

Any ideas on backwards compatibility changes for sprockets 4? I kinda fell into this maintainer role, there's lots of catching up to do. I think instead of using `SassTemplate` we can directly use `SassProcessor`

**Comment by bolandrm** [comment]
That sounds like a reasonable place to start, although for now I'd like to at least maintain support for sprockets 2 / 3 as well.

As far as future compatibility goes, there was a push to get LibSass integrated into sprockets and the default sass-rails (https://github.com/rails/sass-rails/pull/349).   This will be a lot easier for me to finish once we get to upgrading our project to Rails 5 / sprockets 4.

**Comment by schneems** [comment]
I'm working to add deprecations for all of these code points in sprockets 3 right now. I've got some ideas on a patch that would work for this to work with sprockets 2, 3 & 4 (all of which are currently supported via me currently).

**Comment by schneems** [comment]
What I think I would like to do for Sprockets 4 is to fix the built in ScsscProcessor and support sassc natively inside of the `sass-rails` gem, we probably want to encourage people to use sassc over ruby sass due to speed improvements. I see you've contributed to the processors a bit, if you have some time to take a look at the failure https://github.com/rails/sprockets/pull/323#issuecomment-227849634 I would appreciate it. It's very slow going for me since it's an area of the code i've never touched before.
