### ISSUE TITLE
NameError: uninitialized constant Sass::Deprecation error with Sass v3.4.25

### ISSUE THREAD

**Issue by meowsus** [sass/sassc-rails#95]
Sass v3.4.25 was [just released](https://github.com/sass/sass/commit/518c4451ffa537de3c56c451aab1d1e80b956b54) on the 7th, causing sassc-ruby to throw this error:

```
NameError: uninitialized constant Sass::Deprecation
/home/meowsus/Work/engine/core/lib/engine/core.rb:42:in `require'
/home/meowsus/Work/engine/core/lib/engine/core.rb:42:in `<top (required)>'
/home/meowsus/Work/app/config/application.rb:20:in `require'
/home/meowsus/Work/app/config/application.rb:20:in `<top (required)>'
/home/meowsus/Work/app/Rakefile:4:in `require_relative'
/home/meowsus/Work/app/Rakefile:4:in `<top (required)>'
/home/meowsus/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/home/meowsus/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
/home/meowsus/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sass-3.4.25/lib/sass/script/value/string.rb:5:in `<class:String>': uninitialized constant Sass::Deprecation (NameError)
        from /home/meowsus/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sass-3.4.25/lib/sass/script/value/string.rb:4:in `<module:Value>'
        from /home/meowsus/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sass-3.4.25/lib/sass/script/value/string.rb:2:in `<top (required)>'
        from /home/meowsus/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sassc-1.11.2/lib/sassc/script.rb:32:in `require'
        from /home/meowsus/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sassc-1.11.2/lib/sassc/script.rb:32:in `<top (required)>'
        from /home/meowsus/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sassc-1.11.2/lib/sassc.rb:8:in `require_relative'
        from /home/meowsus/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sassc-1.11.2/lib/sassc.rb:8:in `<top (required)>'
        from /home/meowsus/Work/engine/core/lib/engine/core.rb:42:in `require'
        from /home/meowsus/Work/engine/core/lib/engine/core.rb:42:in `<top (required)>'
        from /home/meowsus/Work/app/config/application.rb:20:in `require'
        from /home/meowsus/Work/app/config/application.rb:20:in `<top (required)>'
        from /home/meowsus/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:88:in `require'
        from /home/meowsus/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:88:in `block in server'
        from /home/meowsus/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:85:in `tap'
        from /home/meowsus/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:85:in `server'
        from /home/meowsus/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /home/meowsus/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.4/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

For reference:

Sass: https://github.com/sass/sass/issues/2338
Sassc: https://github.com/sass/sassc/issues/212
Sassc-ruby: https://github.com/sass/sassc-ruby/issues/69

**Comment by meowsus** [comment]
Actually the fix for this is to have https://github.com/sass/sassc-ruby/issues/69 merged and a new version of the gem cut.
